spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store_api?createDatabaseIfNotExist=true
    username: root
    password: Aquasi99
  jpa:
    show-sql: true
websiteURl: "http://localhost:3000"