spring:
  application:
    name: store
  jwt:
    secretKey: ${JWT_SECRET}
    accessTokenExpiration: 7200 #2hr
    refreshTokenExpiration: 604800  #7days
  profiles:
    active: dev
stripe:
  secretKey: ${STRIPE_SECRET_KEY}
  webHookSecretKey: ${STRIPE_WEBHOOK_SECRET_KEY}